# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/adamantium/all/adamantium.rbi
#
# adamantium-0.2.0

module Adamantium
  def __adamantium_dup__; end
  def dup; end
  def self.included(descendant); end
  def transform(&block); end
  def transform_unless(condition, &block); end
end
module Adamantium::ModuleMethods
  def freezer; end
  def included(descendant); end
  def memoize(*methods); end
  def memoize_method(method_name, freezer); end
end
module Adamantium::ClassMethods
  def new(*arg0); end
end
class Adamantium::Freezer
  def self.call(object); end
  def self.freeze_value(value); end
  def self.get(name); end
  def self.new(*arg0); end
  def self.parse(options); end
end
class Adamantium::Freezer::Flat < Adamantium::Freezer
  def self.call(object); end
  def self.freeze(value); end
end
class Adamantium::Freezer::Deep < Adamantium::Freezer
  def self.call(object); end
  def self.freeze(value); end
end
class Adamantium::Freezer::UnknownFreezerError < RuntimeError
end
class Adamantium::Freezer::OptionError < RuntimeError
end
module Adamantium::Mutable
  def freeze; end
  def frozen?; end
end
module Adamantium::Flat
  def freezer; end
  def self.included(descendant); end
end
