# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/anima/all/anima.rbi
#
# anima-0.3.2

class Anima < Module
  def add(*names); end
  def assert_known_attributes(klass, attribute_hash); end
  def attribute_names(&block); end
  def attributes; end
  def attributes_hash(object); end
  def included(descendant); end
  def initialize(*names); end
  def initialize_instance(object, attribute_hash); end
  def new(attributes); end
  def remove(*names); end
  extend Adamantium::ClassMethods
  extend Adamantium::Flat
  extend Adamantium::ModuleMethods
  extend Memoizable::ModuleMethods
  include Adamantium
  include Adamantium::Flat
  include Equalizer::Methods
  include Memoizable
end
class Anima::Error < RuntimeError
  def initialize(klass, missing, unknown); end
end
class Anima::Attribute
  def get(object); end
  def initialize(name); end
  def instance_variable_name; end
  def load(object, attributes); end
  def name; end
  def set(object, value); end
  extend Adamantium::ClassMethods
  extend Adamantium::Flat
  extend Adamantium::ModuleMethods
  extend Memoizable::ModuleMethods
  include Adamantium
  include Adamantium::Flat
  include Equalizer::Methods
  include Memoizable
end
module Anima::InstanceMethods
  def initialize(attributes); end
  def to_h; end
  def with(attributes); end
end
