# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/procto/all/procto.rbi
#
# procto-0.0.3

class Procto < Module
  def included(host); end
  def initialize(name); end
  def self.call(name = nil); end
  def self.new(*arg0); end
end
module Procto::ClassMethods
  def to_proc; end
end
