# typed: false
# frozen_string_literal: true

require:
  - rubocop-sorbet

AllCops:
  NewCops: enable
  Exclude:
    - 'pkg/**/*'
    - 'bin/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Sorbet:
  Enabled: true

Sorbet/EmptyLineAfterSig:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*.rb'

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Naming/HeredocDelimiterNaming:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

# Overrides for tests
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
